#!/bin/bash

if [ $# -lt 3 ]
then
	echo "Must specify an interval and at least two slides:"
	echo "Usage: $0 interval slide slide [slide...]"
fi

interval=$1
slides=(${@:2:$#})

killall fbi
/usr/bin/fbi -noverbose -a -T 1 -t ${interval} --readahead "${slides[@]}"